CREATE TABLE stock (
PRODUCT_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
PRODUCT_IS_AVAILABLE BIT(1) NOT NULL DEFAULT FALSE,
PRODUCT_NAME_EN VARCHAR(128),
PRODUCT_NAME_RU VARCHAR(128),
PRODUCT_DESCRIPTION_EN VARCHAR(255),
PRODUCT_DESCRIPTION_RU VARCHAR(255),
PRODUCT_QUANTITY DOUBLE NOT NULL DEFAULT 0,
PRODUCT_UOM VARCHAR(32),
PRODUCT_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE stock ADD INDEX (PRODUCT_ID);
ALTER TABLE stock ADD INDEX (IS_AVAILABLE);

CREATE TABLE payments (
PAYMENT_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
RECEIPT_ID SMALLINT NOT NULL,
USER_ID SMALLINT NOT NULL,
PRODUCT_ID SMALLINT NOT NULL,
ORDERED_QUANTITY DOUBLE NOT NULL DEFAULT 0.0,
IS_PAID BIT(1) NOT NULL DEFAULT FALSE,
PAYMENT_DATE DATE,
PAYMENT_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE payments ADD INDEX (PAYMENT_ID);
ALTER TABLE payments ADD INDEX (RECEIPT_ID);
ALTER TABLE payments ADD INDEX (PAYMENT_DATE);

CREATE TABLE receipts (
RECEIPT_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
USER_ID SMALLINT NOT NULL,
IS_PAID BIT(1) NOT NULL DEFAULT FALSE,
IS_CANCELLED BIT(1) NOT NULL DEFAULT FALSE,
TRANSACTION_DATE DATE,
RECEIPT_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE payments ADD INDEX (RECEIPT_ID);
ALTER TABLE payments ADD INDEX (USER_ID);

CREATE TABLE users (
USER_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
USER_NAME VARCHAR(128),
USER_PASSWORD VARCHAR(128),
IS_CLIENT BIT(1) NOT NULL DEFAULT TRUE,
IS_CASHIER BIT(1) NOT NULL DEFAULT FALSE,
IS_SENIOR_CASHIER BIT(1) NOT NULL DEFAULT FALSE,
IS_MERCHANT BIT(1) NOT NULL DEFAULT FALSE,
USER_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE users ADD INDEX (USER_ID);
ALTER TABLE users ADD INDEX (USER_NAME);