START TRANSACTION;
CREATE TABLE stock (
PRODUCT_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
IS_AVAILABLE BIT(1) NOT NULL DEFAULT FALSE,
PRODUCT_NAME_EN VARCHAR(128),
PRODUCT_NAME_RU VARCHAR(128),
PRODUCT_DESCRIPTION_EN VARCHAR(255),
PRODUCT_DESCRIPTION_RU VARCHAR(255),
PRODUCT_COST DOUBLE NOT NULL DEFAULT 0,
PRODUCT_QUANTITY DOUBLE NOT NULL DEFAULT 0,
PRODUCT_UOM_EN VARCHAR(32) NOT NULL,
PRODUCT_UOM_RU VARCHAR(32) NOT NULL,
PRODUCT_NOTES_EN VARCHAR(255),
PRODUCT_NOTES_RU VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE stock ADD INDEX (PRODUCT_ID);
ALTER TABLE stock ADD INDEX (IS_AVAILABLE);

CREATE TABLE payments (
PAYMENT_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
ORDER_ID SMALLINT NOT NULL,
PRODUCT_ID SMALLINT NOT NULL,
QUANTITY DOUBLE NOT NULL DEFAULT 0,
IS_PAID BIT(1) NOT NULL DEFAULT FALSE,
PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PAYMENT_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE payments ADD INDEX (PAYMENT_ID);
ALTER TABLE payments ADD INDEX (ORDER_ID);
ALTER TABLE payments ADD INDEX (PAYMENT_DATE);

CREATE TABLE orders (
ORDER_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
USER_ID SMALLINT NOT NULL,
IS_APPROVED BIT(1) NOT NULL DEFAULT FALSE,
IS_CANCELLED BIT(1) NOT NULL DEFAULT FALSE,
ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ORDER_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE orders ADD INDEX (ORDER_ID);
ALTER TABLE orders ADD INDEX (USER_ID);

CREATE TABLE users (
USER_ID SMALLINT NOT NULL AUTO_INCREMENT KEY,
USER_NAME VARCHAR(128),
USER_PASSWORD VARCHAR(128),
IS_CLIENT BIT(1) NOT NULL DEFAULT TRUE,
IS_CASHIER BIT(1) NOT NULL DEFAULT FALSE,
IS_SENIOR_CASHIER BIT(1) NOT NULL DEFAULT FALSE,
IS_MERCHANT BIT(1) NOT NULL DEFAULT FALSE,
USER_NOTES VARCHAR(255)
) ENGINE InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE users ADD INDEX (USER_ID);
ALTER TABLE users ADD INDEX (USER_NAME);
COMMIT;