package com.epam.project;

import com.epam.project.dao.*;
import com.epam.project.entities.*;
import com.epam.project.exceptions.DataBaseConnectionException;
import com.epam.project.exceptions.DataBaseNotSupportedException;
import com.epam.project.exceptions.IncorrectPropertyException;

import java.util.List;

public class Application {

    private static IProductDao productDao;
    private static List<Product> products;
    private static IUserDao userDao;
    private static List<User> users;
    private static IOrderDao orderDao;
    private static List<Order> orders;
    private static IPaymentDao paymentDao;
    private static List<Payment> payments;

    public Application() throws DataBaseNotSupportedException, IncorrectPropertyException {
        DaoFactory daoFactory = DaoFactory.getDaoFactory(DataBaseSelector.MY_SQL);
        productDao = daoFactory.getProductDao();
        userDao = daoFactory.getUserDao();
        orderDao = daoFactory.getOrderDao();
    }

    public static void main(String... args) throws Exception {
        Application application = new Application();
        //application.testProductDao();
        //application.testUserDao();
        //System.out.println(order)
        application.testPaymentDao();
    }

    public void testUserDao() {
        User user = new User("Somebody", "else");
            user.setUserRole(UserRole.SENIOR_CASHIER);
            user.setNotes("Added by Application runner");
        //System.out.println(userDao.addUserToDB(user));
        //System.out.println(userDao.updateUserInDB(user));
        System.out.println(userDao.deleteUserFromDB(user));
        System.out.println("All users\n");
        users = userDao.findAllUsersInDB();
        System.out.println(users);
        System.out.println("\nUser by name = Yaroslav");
        System.out.println(userDao.findUserByName("Yaroslav"));
    }

    public void testPaymentDao() throws DataBaseConnectionException{
        paymentDao = new PaymentDaoImpl();
        System.out.println("All payments\n");
        payments = paymentDao.findAllPayments();
        System.out.println(payments);
        System.out.println("\nPayments by order code 1:");
        payments = paymentDao.findAllPaymentsByOrderCode(1L);
        System.out.println(payments);
        System.out.println("\nPayments by id 1:");
        Payment payment = paymentDao.findPaymentById(1);
        System.out.println(payment);

    }

    public void testProductDao() {
        Product product = new Product().addCode("C001A").addAvailable(true)
                .addNameEn("Royal Canin Kitten 0 - 3").addNameRu("Royal Canin Kitten 0 - 3")
                .addDescriptionEn("Royal Canin dry feed for kittens 0 - 3 month")
                .addDescriptionRu("Корм Роял Канин для котят в возрасте 0 - 3 месяцeв")
                .addCost(247.50).addQuantity(50.0)
                .addUomEn("kg").addUomRu("кг")
                .addNotesEn("Added by Application runner").addNotesRu("Сгенерировано классом Application");
        //System.out.println(productDao.addProductToDB(product));
        //System.out.println(productDao.updateProductInDB(product));
        //productDao.updateProductInDB(product);
        System.out.println(productDao.deleteProductFromDB("C001A"));
        System.out.println("All products\n");
        products = productDao.findAllProductsInDB();
        System.out.println(products);
        System.out.println("\nProduct by id = 11");
        System.out.println(productDao.findProductById(11));
        System.out.println("\nProduct by code = D005");
        System.out.println(productDao.findProductByCode("D005"));
    }

    /*public void testOrderDao(){
        Order order = createTestOrder(4, 6, "D001", "C001");
        System.out.println(orderDao.addOrderToDB(order));
        System.out.println("All orders\n");
        orders = orderDao.findAllOrders();
        System.out.println(orders);
        /*System.out.println("\nOrders by User id = 1");
        System.out.println(orderDao.findAllOrdersByUser(1));
        System.out.println("\nOrders by id = 2");
        System.out.println(orderDao.findOrderById(3));
    }*/

    /*public Order createTestOrder(Integer orderNum, Integer userId, String... productCodes) {
        Order order = new Order();
        order.setOrderId(orderNum);
        order.setUserId(userId);
        order.setUserName(userDao.findUserById(userId).getName());
        order.setOrderStatus(OrderStatus.CREATED);
        order.setOrderDate(new Timestamp(System.currentTimeMillis()));
        order.setNotes("Generated by Application runner");
        for (String code : productCodes)
            order.addProduct(productDao.findProductByCode(code), 30.0);
        return order;
    }*/
}
